### ISSUE TITLE
[dunfell] livebook: module Mix is not available

### ISSUE THREAD

**Issue by yangm97** [meta-erlang/meta-erlang#244]
```
** (UndefinedFunctionError) function Mix.install/1 is undefined (module Mix is not available)
    Mix.install([kino: "~> 0.5.0"])
```

`local.conf`

```
    PREFERRED_VERSION_erlang = "24.3.4.11"
    PREFERRED_VERSION_erlang-native = "24.3.4.11"

    PREFERRED_VERSION_rebar3 = "3.20.0"
    PREFERRED_VERSION_rebar3-native = "3.20.0"
```

`repos`

```
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    refspec: 78fe96f3edf981285cb9b6a0286e45f44d8b4b21
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    refspec: 814eec96c2a29172da57a425a3609f8b6fcc6afe
    layers:
      meta-oe:
      meta-filesystems:
      meta-python:
      meta-networking:
      meta-perl:

  meta-sunxi:
    url: "https://github.com/linux-sunxi/meta-sunxi"
    refspec: f367a1ff2c329c801659c6de77910456a4167430

  meta-mender:
    url: "https://github.com/mendersoftware/meta-mender"
    refspec: 45041cfb7b05c2ff44204d592b200493b25ed8ae
    layers:
      meta-mender-core:

  meta-mender-community:
    url: "https://github.com/mendersoftware/meta-mender-community"
    refspec: 91122992c85cb18a0daffcde76b6c59116e723b9
    layers:
      meta-mender-sunxi:

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    refspec: b556bc7953b4294fb65520b9ed4663cbdeff3607

  meta-security:
    url: "https://git.yoctoproject.org/meta-security"
    refspec: b76698c788cb8ca632077a972031899ef15025d6

  meta-erlang:
    url: "https://github.com/meta-erlang/meta-erlang"
    refspec: e9d1a05ae65e712d9312c5a9183ecc69dd57a068
```
